### PR TITLE
8 posts belong to users

### LINKED ISSUE #25: 11-posts-belong-to-users
Posts should belong to a user, and the user's name should be displayed alongside each post.

### PR DESCRIPTION
**Pull request by KyeBracey**
Closes #25

### CODE REVIEW

**Comment by dmcd84** [comment]
:shipit:

**Review by jjadeseravla — APPROVED** [review]
:shipit: 

🚋

**Comment by Kynosaur** [comment]
Closes #25

**Comment by KyeBracey** [comment]
Closes #25

**Pull request closed without merging**
