### PR TITLE
Adds a delightfully informative README

### PR DESCRIPTION
**Pull request by wemmm**

### CODE REVIEW

**Review by KyeBracey — COMMENTED** [review]
Both delightful and informative! :shipit:

**Review by jjadeseravla — APPROVED** [review]
:shipit:

**Comment by dmcd84** [comment]
👍

**Comment by dmcd84** [comment]
:shipit:

**Comment by Kynosaur** [comment]
Closes #22

**Comment by KyeBracey** [comment]
Closes #22

**Pull request closed without merging**
